MONGO_CLIENT = "mongodb://localhost:27017/"
DEV_MONGO_CLIENT = "mongodb+srv://ruchi:ruchi123@todoist-cluster.u4fvk.mongodb.net/todoist?retryWrites=true&w=majority"
DATABASE = "todoist"
USER_COLLECTION = "users"
TASK_DATA_COLLECTION = "taskData"
